name: pairedit
channels:
  - https://repo.anaconda.com/pkgs/main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - ca-certificates=2024.8.30=hbcca054_0
  - comm=0.2.2=pyhd8ed1ab_0
  - debugpy=1.8.5=py39hf88036b_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - executing=2.1.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py39hf3d152e_0
  - krb5=1.21.3=h143b758_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libedit=3.1.20230828=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgomp=14.1.0=h77fa898_1
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.2=py39h06a4308_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=6.0.0=py39h8cd3c5a_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.3=pyhd8ed1ab_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - python=3.9.19=h955ad1f_1
  - python_abi=3.9=2_cp39
  - pyzmq=26.2.0=py39h4e4fb57_2
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.1=py39h8cd3c5a_1
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024a=h04d1e81_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zeromq=4.3.5=ha4adb4c_5
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.2.1
      - annotated-types==0.7.0
      - attrs==25.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.13.3
      - bitsandbytes==0.41.1
      - bleach==6.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmake==3.30.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - dadaptation==3.1
      - defusedxml==0.7.1
      - diffusers==0.31.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - fastjsonschema==2.21.1
      - filelock==3.16.0
      - fonttools==4.53.1
      - fsspec==2024.9.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.66.2
      - huggingface-hub==0.27.0
      - idna==3.8
      - importlib-metadata==8.4.0
      - ipython==8.7.0
      - ipywidgets==8.1.5
      - jinja2==3.1.4
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - lion-pytorch==0.1.2
      - lit==18.1.8
      - lpips==0.1.4
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.6.2
      - mistune==3.1.3
      - mpmath==1.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.2.1
      - numpy==1.23.5
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.5.5.64
      - opencv-python-headless==4.7.0.68
      - pandas==1.5.2
      - pandocfilters==1.5.1
      - pathtools==0.1.2
      - peft==0.14.0
      - pillow==10.1.0
      - pipreqs==0.5.0
      - prodigyopt==1.0
      - promise==2.3
      - protobuf==3.20.3
      - pydantic==2.6.3
      - pydantic-core==2.16.3
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.1
      - referencing==0.36.2
      - regex==2024.7.24
      - requests==2.31.0
      - rpds-py==0.24.0
      - safetensors==0.4.5
      - scipy==1.13.1
      - sentencepiece==0.2.0
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - shortuuid==1.0.13
      - smmap==5.0.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - torch==2.5.0+cu121
      - torchaudio==2.5.0+cu121
      - torchvision==0.20.0+cu121
      - tqdm==4.64.1
      - transformers==4.47.1
      - triton==3.1.0
      - urllib3==2.2.2
      - wandb==0.12.21
      - webencodings==0.5.1
      - werkzeug==3.0.4
      - widgetsnbextension==4.0.13
      - xformers==0.0.28.post3
      - yarg==0.1.9
      - zipp==3.20.1
